# Makefile for lect17 

all: studentBot classexample 

studentBot: studentBot.cpp
	g++ studentBot.cpp -o studentBot -std=c++17 -Wall

classexample: classexample.cpp
	g++ classexample.cpp -o classexample -std=c++17 -Wall

clean:
	rm -f studentBot classexample a.out *o
